select sum(attendance) as total_attendance from cfb_game_stats;

select down from cfb_play where play_type='PENALTY' group by down order by count(down) desc limit 1;

select distinct(cfb_team.name) as name, A.rate from (select X.team_id as id, (Y.touchdown_total/X.red_zone_attempt_total) as rate from (select cfb_drive.team_id, count(cfb_drive.team_id) as red_zone_attempt_total from cfb_drive where red_zone_attempt=1 group by cfb_drive.team_id having red_zone_attempt_total>=10) X inner join (select cfb_drive.team_id, count(cfb_drive.team_id) as touchdown_total from cfb_drive where red_zone_attempt=1 and end_reason='TOUCHDOWN' group by cfb_drive.team_id) Y on X.team_id=Y.team_id) A, cfb_team where cfb_team.team_id = A.id order by rate desc, name desc limit 5;

select distinct cfb_conference.name as conference_id, avg(X.duration) as duration from (select cfb_game.game_id as game_id, cfb_game.visit_team_id as visit_team_id, cfb_game.home_team_id as home_team_id, cfb_game_stats.duration as duration from cfb_game inner join cfb_game_stats on cfb_game.game_id=cfb_game_stats.game_id) X, cfb_team, cfb_conference where X.visit_team_id=cfb_team.team_id and cfb_team.conference_id=cfb_conference.conference_id group by conference_id order by duration desc limit 1;

select distinct cfb_player.first_name, cfb_player.last_name from cfb_player, (select cfb_pass.receiver_player_id, sum(yards) as yds from cfb_play, cfb_pass, (select distinct player_id from cfb_player) cfb_player, cfb_game where cfb_game.game_id = cfb_play.game_id and cfb_pass.game_id = cfb_play.game_id and cfb_player.player_id = cfb_pass.receiver_player_id and cfb_play.play_number = cfb_pass.play_number and cfb_pass.first_down = 1 and month(cfb_game.game_date)=10 group by receiver_player_id union select cfb_pass.passer_player_id, sum(yards) as yds from cfb_play, cfb_pass, (select distinct player_id from cfb_player) cfb_player, cfb_game where cfb_game.game_id = cfb_play.game_id and cfb_pass.game_id = cfb_play.game_id and cfb_player.player_id = cfb_pass.passer_player_id and cfb_play.play_number = cfb_pass.play_number and cfb_pass.first_down = 1 and month(cfb_game.game_date)=10 group by passer_player_id union select cfb_rush.player_id, sum(yards) as yds from cfb_play, cfb_rush, (select distinct player_id from cfb_player) cfb_player, cfb_game where cfb_game.game_id = cfb_play.game_id and cfb_rush.game_id = cfb_play.game_id and cfb_player.player_id = cfb_rush.player_id and cfb_play.play_number = cfb_rush.play_number and cfb_rush.first_down = 1 and month(cfb_game.game_date)=10 group by player_id order by yds desc limit 1) A where cfb_player.player_id = A.receiver_player_id;

select state.homestate, state.number, (state.number/stateTotal.count) as percent from (select homestate, count(homestate) as number  from cfb_player where team_id=513 group by homestate order by count(homestate) desc) state, (select count(*) as count from cfb_player where team_id=513 and homestate!='NULL') stateTotal limit 1;

select count(A.player_id) as players from (select player_id from cfb_player group by player_id having count(player_id)>=3) A;

select distinct B.first_name, B.last_name, cfb_team.name, B.year from cfb_team, (select cfb_player.first_name as first_name, cfb_player.last_name as last_name, A.team_id as team_id, A.year as year from cfb_player, (select cfb_pass.receiver_player_id as receiver_player_id, cfb_pass.team_id as team_id, cfb_pass.yards, year(cfb_game.game_date) as year from cfb_pass, cfb_play, cfb_game where cfb_play.game_id=cfb_pass.game_id and cfb_play.play_number=cfb_pass.play_number and cfb_play.period=4 and cfb_pass.completion=1 and cfb_pass.yards>=ALL(select cfb_pass.yards from cfb_pass, cfb_play where cfb_play.game_id=cfb_pass.game_id and cfb_play.play_number=cfb_pass.play_number and cfb_play.period=4 and cfb_pass.completion=1) and cfb_game.game_id=cfb_play.game_id) A where cfb_player.player_id=A.receiver_player_id) B where cfb_team.team_id=B.team_id;

select A.name, year(A.game_date) as year, sum(A.attendance) as attendance from (select cfb_game.game_date as game_date, cfb_game_stats.attendance as attendance, cfb_team.name as name from cfb_game, cfb_game_stats, cfb_team where cfb_game.game_id=cfb_game_stats.game_id and cfb_game.home_team_id=cfb_team.team_id group by cfb_team.name, cfb_game.game_date, cfb_game_stats.attendance order by cfb_game_stats.attendance desc) A group by A.name, year order by attendance desc limit 5;
